forum/src/main/java/forum/Controller/JpaServlet.java
package forum.Controller;

import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;

import forum.Model.JpaUtil;

public class JpaServlet extends HttpServlet {

	public void init(ServletConfig config) throws ServletException {
		JpaUtil.start();		
	}

}

forum/src/main/java/forum/Controller/UsuarioLogadoController.java
package forum.Controller;
import forum.Model.*;

import java.io.IOException;  

import javax.annotation.PostConstruct;  
import javax.faces.application.FacesMessage;  
import javax.faces.bean.ManagedBean;  
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;  
import javax.faces.context.FacesContext;  
  
@ManagedBean(name="UsuarioLogadoController")
@SessionScoped  
public class UsuarioLogadoController {  
     
	//@ManagedProperty(value="#{usuarioService}")
	private UsuarioService usuarioService = new UsuarioService();
    
	//@ManagedProperty(value="#{user}")
	private Usuario user = new Usuario();
	private Usuario userSession = new Usuario();
    private Boolean usuarioLogado = false;  
      
    private static UsuarioLogadoController instance;  
  
    @PostConstruct  
    public void inicializa()  
    {  
        //user = new Usuario();  
        usuarioLogado = Boolean.FALSE;  
        instance = this;  
    }  
    
    //Verifica se existe usuario logado na sessao
    public static UsuarioLogadoController getInstance() throws Exception  
    {  
        if(instance == null)  
        {  
            throw new Exception("Não há usuario logado no sistema.");  
        }  
        return instance;  
    }  
      //desloga o usuario.
    public void logout()  
    {  
        this.userSession = null;  
        FacesContext.getCurrentInstance().getExternalContext().invalidateSession();  
    }  
      
    public void fazerLogin()  
    {  
	    try {  

        	Usuario u = usuarioService.logar(user);  
            if(u == null)  
            {  
                FacesContext.getCurrentInstance().addMessage(null,   
                    new FacesMessage(FacesMessage.SEVERITY_ERROR, "Erro teste", "Usuario não encontrado ou senha incorreta, tente novamente."));  
            }  
            else  
            {  
                usuarioLogado = true;  
                userSession = u;
                FacesContext.getCurrentInstance().addMessage(null,   
                        new FacesMessage(FacesMessage.SEVERITY_INFO, "Login Efetuado com sucesso!", "Erro ao efetuar login, tente novamente."));
            }  
              
        } catch (Exception e) {  
            FacesContext.getCurrentInstance().addMessage(null,   
                    new FacesMessage(FacesMessage.SEVERITY_ERROR, "Erro ao efetuar login, tente novamente! Digite E-mail e Senha Validos", "Erro ao efetuar login, tente novamente."));  
        }
	    System.out.println(userSession.getCidade()+" usuariologado456");
    }  

	public String getNomeUsuario() //throws IOException  
    {  
		System.out.println(userSession.getCidade()+" usuariologado2");
		if(usuarioLogado)  
        {  
           return user.getEmail();  
        }else{    
        return "Login";  
    } }
     
    public Usuario getUser() {  
        return user;  
    }  
  
    public void setUser(Usuario user) {  
        this.user = user;  
    }
    
    public int getID_User(){
    	int i = userSession.getId_user();
    	return i;
    }
    
    public String getEmail(){
    	String i = userSession.getEmail();
    	return i;
    }
    
    public String getData(){
    	String i = userSession.getData_nascimento();
    	return i;
    }
    
    public String getNome(){
    	String i = userSession.getNome();
    	return i;
    }
    public String getCidade(){
    	String i = userSession.getCidade();
    	return i;
    }
    public String getUF(){
    	String i = userSession.getUf();
    	return i;
    }
      
}  

forum/src/main/webapp/CadastroUsuario.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:o="http://openfaces.org/"
	xmlns:c="http://java.sun.com/jsp/jstl/core" >

<h:head>
	<meta charset="utf-8"></meta>
	<meta http-equiv="X-UA-Compatible" content="IE=edge"></meta>
	<meta name="viewport" content="width=device-width, initial-scale=1"></meta>
	<meta name="description" content=""></meta>
	<meta name="author" content=""></meta>
	<link rel="shortcut icon" href="../../assets/ico/favicon.ico"></link>

	<!-- JS -->
	<script type="text/javascript" src="js/jquery.js"></script>
	<script type="text/javascript" src="js/validacao_email.js"></script>

	<!-- CSS -->
	<link href="bootstrap3/css/bootstrap.css" rel="stylesheet"></link>
	<link href="bootstrap3/css/bootstrap-theme.css" rel="stylesheet"></link>
	<link href="css/carousel.css" rel="stylesheet"></link>
	<link href="css/validacao_css.css" rel="stylesheet"></link>
	<title>Novo Usuario</title>
</h:head>
<h:body>
	<div class="navbar-wrapper">
		<div class="container">

			<div class="navbar navbar-inverse navbar-static-top">
				<div class="container">
					<div class="navbar-collapse collapse">
						<ul class="nav navbar-nav">
						<li><a href="index.xhtml">Home</a></li>
							<li><a href="forum.xhtml">Forum</a></li>
							<li><a href="Construcao.xhtml">Conheça o HTML 5</a></li>
							<li><a href="Contato.xhtml">Contato</a></li>
							<li><a href="CadastroUsuario.xhtml">Novo Cadastro</a></li>
							<c:if test="${UsuarioLogadoController.getEmail() != null}">
								<li><a href="UsuarioInformacoes.xhtml">Informações do Usuario</a></li>
							</c:if>
						</ul>
						<c:if test="${UsuarioLogadoController.getEmail() != null}">
							<ul>

								<li><h:outputText style="font-weight:bold" />
									<div class="btn-group">
										<button type="button" class="btn btn-primary dropdown-toggle"
											data-toggle="dropdown" onclick="location.href='login.xhtml'">
											<h:outputText value="#{UsuarioLogadoController.getEmail()}"
												style="font-weight:bold"></h:outputText>
											<span class="glyphicon glyphicon-user"></span> <span
												class="caret"></span>
										</button>
									</div></li>
							</ul>
						</c:if>
						<c:if test="${UsuarioLogadoController.getEmail() eq null}">
							<ul>

								<li><h:outputText style="font-weight:bold" />
									<div class="btn-group">
										<button type="button" class="btn btn-primary dropdown-toggle"
											data-toggle="dropdown" onclick="location.href='login.xhtml'">
											Login
											<span class="glyphicon glyphicon-user"></span> <span
												class="caret"></span>
										</button>
									</div></li>
							</ul>
						</c:if>

					</div>


				</div>
			</div>
		</div>

	</div>

	<div class="container" align="center">
		<br /> <br /> <br /> <br /> <br />
		<h2>Cadastre-se e seja um membro do forum HTML Livre</h2>
		<h4>Preencha todos os campos</h4>
		<h:form>
			<table>
				<div class="input-group"></div>
				<tr>

					<tr>
						<td><span class="label label-info">E-Mail:</span> <!-- E-mail -->
							<h:inputText value="#{cadastroUsuario.usuario.email}"
								p:placeholder="E-mail" name="e-mail" class="form-control"
								id="email" onblur="checar()"></h:inputText></td>
					</tr>

					<tr>
						<td><span class="label label-info">Senha:</span> <!-- Senha -->
							<h:inputSecret value="#{cadastroUsuario.usuario.senha}"
								p:placeholder="Senha" name="senha" class="form-control"
								id="senha" onblur="checar()"></h:inputSecret></td>
					</tr>
					<tr>
						<td><span class="label label-info">Nome</span> <!-- Nome -->
							<h:inputText value="#{cadastroUsuario.usuario.nome}"
								p:placeholder="Nome" name="nome" class="form-control" id="nome"></h:inputText>
						</td>
					</tr>
					<tr>
						<td><span class="label label-info ">Data de Nascimento</span>
							<!-- Data de Nascimento --> <h:inputText
								value="#{cadastroUsuario.usuario.data_nascimento}"
								p:placeholder="Data de Nascimneto" name="data"
								class="form-control" id="data"></h:inputText></td>
					</tr>
					<tr>
						<td><span class="label label-info">Sexo</span> <!-- Sexo -->
							<h:inputText value="#{cadastroUsuario.usuario.sexo}"
								p:placeholder="Sexo" name="sexo" class="form-control" id="sexo"></h:inputText>
						</td>
					</tr>
					<tr>
						<td><span class="label label-info">Cidade</span> <!-- Cidade -->
							<h:inputText value="#{cadastroUsuario.usuario.cidade}"
								p:placeholder="Cidade" name="cidade" class="form-control"
								id="cidade"></h:inputText></td>
					</tr>
					<tr>
						<td><span class="label label-info">Estado</span> <!-- Cidade -->
							<h:inputText value="#{cadastroUsuario.usuario.uf}"
								p:placeholder="Estado" name="estado" class="form-control"
								id="estado"></h:inputText></td>
					</tr>
				</tr>
			</table>
			<tr>
				<h:commandButton value="Efetuar Cadastro"
					action="#{cadastroUsuario.salvar}" />
				<button type="button" onclick="location.href='index.jsp'">Cancelar</button>
			</tr>
		</h:form>
	</div>
</h:body>
</html>

forum/src/main/webapp/Construcao.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core" >


<h:head>
	<meta charset="utf-8"></meta>
	<meta http-equiv="X-UA-Compatible" content="IE=edge"></meta>
	<meta name="viewport" content="width=device-width, initial-scale=1"></meta>
	<meta name="description" content=""></meta>
	<meta name="author" content=""></meta>
	<link rel="shortcut icon" href="../../assets/ico/favicon.ico"></link>

	<!-- JS -->
	<script type="text/javascript" src="js/jquery.js"></script>
	<script type="text/javascript" src="js/validacao_email.js"></script>
	<script type="text/javascript" src="js/forum.js"></script>

	<!-- CSS -->
	<link href="bootstrap3/css/bootstrap.css" rel="stylesheet"></link>
	<link href="bootstrap3/css/bootstrap-theme.css" rel="stylesheet"></link>
	<link href="css/carousel.css" rel="stylesheet"></link>
	<link href="css/validacao_css.css" rel="stylesheet"></link>
	<link href="css/forum.css" rel="stylesheet"></link>
	<title>Novo Tópico</title>
</h:head>
<h:body>
	<div class="navbar-wrapper">
		<div class="container">

			<div class="navbar navbar-inverse navbar-static-top">
				<div class="container">
					<div class="navbar-collapse collapse">
						<ul class="nav navbar-nav">
						<li><a href="index.xhtml">Home</a></li>
							<li><a href="forum.xhtml">Forum</a></li>
							<li><a href="Construcao.xhtml">Conheça o HTML 5</a></li>
							<li><a href="Contato.xhtml">Contato</a></li>
							<li><a href="CadastroUsuario.xhtml">Novo Cadastro</a></li>
							<c:if test="${UsuarioLogadoController.getEmail() != null}">
								<li><a href="UsuarioInformacoes.xhtml">Informações do Usuario</a></li>
							</c:if>
						</ul>
						<c:if test="${UsuarioLogadoController.getEmail() != null}">
							<ul>

								<li><h:outputText style="font-weight:bold" />
									<div class="btn-group">
										<button type="button" class="btn btn-primary dropdown-toggle"
											data-toggle="dropdown" onclick="location.href='login.xhtml'">
											<h:outputText value="#{UsuarioLogadoController.getEmail()}"
												style="font-weight:bold"></h:outputText>
											<span class="glyphicon glyphicon-user"></span> <span
												class="caret"></span>
										</button>
									</div></li>
							</ul>
						</c:if>
						<c:if test="${UsuarioLogadoController.getEmail() eq null}">
							<ul>

								<li><h:outputText style="font-weight:bold" />
									<div class="btn-group">
										<button type="button" class="btn btn-primary dropdown-toggle"
											data-toggle="dropdown" onclick="location.href='login.xhtml'">
											Login
											<span class="glyphicon glyphicon-user"></span> <span
												class="caret"></span>
										</button>
									</div></li>
							</ul>
						</c:if>

					</div>


				</div>
			</div>
		</div>

	</div>

	<img id="img_const" src="imagens/construcao_final.png"></img>



	<!-- FOOTER -->
	<footer>
	<p class="pull-right">
		<a href="#">Back to top</a>
	</p>
	<p>
		&copy; 2014 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a
			href="#">Terms</a>
	</p>
	</footer>

</h:body>
</html>

forum/src/main/webapp/Contato.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core">


<h:head>
	<meta charset="utf-8"></meta>
	<meta http-equiv="X-UA-Compatible" content="IE=edge"></meta>
	<meta name="viewport" content="width=device-width, initial-scale=1"></meta>
	<meta name="description" content=""></meta>
	<meta name="author" content=""></meta>
	<link rel="shortcut icon" href="../../assets/ico/favicon.ico"></link>

	<!-- JS -->
	<script type="text/javascript" src="js/jquery.js"></script>
	<script type="text/javascript" src="js/validacao_email.js"></script>
	<script type="text/javascript" src="js/forum.js"></script>

	<!-- CSS -->
	<link href="bootstrap3/css/bootstrap.css" rel="stylesheet"></link>
	<link href="bootstrap3/css/bootstrap-theme.css" rel="stylesheet"></link>
	<link href="css/carousel.css" rel="stylesheet"></link>
	<link href="css/validacao_css.css" rel="stylesheet"></link>
	<link href="css/forum.css" rel="stylesheet"></link>
	<title>Novo Tópico</title>
</h:head>
<h:body>
	<div class="navbar-wrapper">
		<div class="container">

			<div class="navbar navbar-inverse navbar-static-top">
				<div class="container">
					<div class="navbar-collapse collapse">
						<ul class="nav navbar-nav">
						<li><a href="index.xhtml">Home</a></li>
							<li><a href="forum.xhtml">Forum</a></li>
							<li><a href="Construcao.xhtml">Conheça o HTML 5</a></li>
							<li><a href="Contato.xhtml">Contato</a></li>
							<li><a href="CadastroUsuario.xhtml">Novo Cadastro</a></li>
							<c:if test="${UsuarioLogadoController.getEmail() != null}">
								<li><a href="UsuarioInformacoes.xhtml">Informações do Usuario</a></li>
							</c:if>
						</ul>
						<c:if test="${UsuarioLogadoController.getEmail() != null}">
							<ul>

								<li><h:outputText style="font-weight:bold" />
									<div class="btn-group">
										<button type="button" class="btn btn-primary dropdown-toggle"
											data-toggle="dropdown" onclick="location.href='login.xhtml'">
											<h:outputText value="#{UsuarioLogadoController.getEmail()}"
												style="font-weight:bold"></h:outputText>
											<span class="glyphicon glyphicon-user"></span> <span
												class="caret"></span>
										</button>
									</div></li>
							</ul>
						</c:if>
						<c:if test="${UsuarioLogadoController.getEmail() eq null}">
							<ul>

								<li><h:outputText style="font-weight:bold" />
									<div class="btn-group">
										<button type="button" class="btn btn-primary dropdown-toggle"
											data-toggle="dropdown" onclick="location.href='login.xhtml'">
											Login <span class="glyphicon glyphicon-user"></span> <span
												class="caret"></span>
										</button>
									</div></li>
							</ul>
						</c:if>

					</div>


				</div>
			</div>
		</div>

	</div>
	<center>
		<div>
			<br></br>
			<br></br>
			<br></br>
			<br></br>
			<br></br>
			<br></br>
			<br></br> <img src="imagens/email.jpg" width="40" height="40"></img>
			aleixojr@outlook.com <br></br> <img src="imagens/email.jpg"
				width="40" height="40"></img> joseneto.design@gmail.com <br></br> <img
				src="imagens/email.jpg" width="40" height="40"></img>
			paulovitornn@gmail.com <br></br> <img src="imagens/email.jpg"
				width="40" height="40"></img> raizza.si@gmail.com <br></br> <a
				href="http://www.facebook.com.br/forumhtml5"><img
				src="imagens/Cracked-Facebook-Logo.png" width="60" height="60"></img></a>
			<h5>curta nossa página no facebook</h5>
		</div>
	</center>
	<!-- FOOTER -->
	<footer>
	<p class="pull-right">
		<a href="#">Back to top</a>
	</p>
	<p>
		&copy; 2014 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a
			href="#">Terms</a>
	</p>
	</footer>

</h:body>
</html>

forum/src/main/webapp/login.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:o="http://openfaces.org/"
	xmlns:c="http://java.sun.com/jsp/jstl/core" >
<br/>
<h:head>
	<meta charset="utf-8"></meta>
	<meta http-equiv="X-UA-Compatible" content="IE=edge"></meta>
	<meta name="viewport" content="width=device-width, initial-scale=1"></meta>
	<meta name="description" content=""></meta>
	<meta name="author" content=""></meta>
	<link rel="shortcut icon" href="../../assets/ico/favicon.ico"></link>

	<!-- JS -->
	<script type="text/javascript" src="js/jquery.js"></script>
	<script type="text/javascript" src="js/validacao_email.js"></script>

	<!-- CSS -->
	<link href="bootstrap3/css/bootstrap.css" rel="stylesheet"></link>
	<link href="bootstrap3/css/bootstrap-theme.css" rel="stylesheet"></link>
	<link href="css/carousel.css" rel="stylesheet"></link>
	<link href="css/validacao_css.css" rel="stylesheet"></link>
	<title>Novo Tópico</title>
</h:head>
<h:body>
	<div class="navbar-wrapper">
		<div class="container">

			<div class="navbar navbar-inverse navbar-static-top">
				<div class="container">
					<div class="navbar-collapse collapse">
						<ul class="nav navbar-nav">
						<li><a href="index.xhtml">Home</a></li>
							<li><a href="forum.xhtml">Forum</a></li>
							<li><a href="Construcao.xhtml">Conheça o HTML 5</a></li>
							<li><a href="Contato.xhtml">Contato</a></li>
							<li><a href="CadastroUsuario.xhtml">Novo Cadastro</a></li>
							<c:if test="${UsuarioLogadoController.getEmail() != null}">
								<li><a href="UsuarioInformacoes.xhtml">Informações do Usuario</a></li>
							</c:if>
						</ul>
						<c:if test="${UsuarioLogadoController.getEmail() != null}">
							<ul>

								<li><h:outputText style="font-weight:bold" />
									<div class="btn-group">
										<button type="button" class="btn btn-primary dropdown-toggle"
											data-toggle="dropdown" onclick="location.href='login.xhtml'">
											<h:outputText value="#{UsuarioLogadoController.getEmail()}"
												style="font-weight:bold"></h:outputText>
											<span class="glyphicon glyphicon-user"></span> <span
												class="caret"></span>
										</button>
									</div></li>
							</ul>
						</c:if>
						<c:if test="${UsuarioLogadoController.getEmail() eq null}">
							<ul>

								<li><h:outputText style="font-weight:bold" />
									<div class="btn-group">
										<button type="button" class="btn btn-primary dropdown-toggle"
											data-toggle="dropdown" onclick="location.href='login.xhtml'">
											Login
											<span class="glyphicon glyphicon-user"></span> <span
												class="caret"></span>
										</button>
									</div></li>
							</ul>
						</c:if>

					</div>


				</div>
			</div>
		</div>

	</div>
<c:if test="${UsuarioLogadoController.getEmail() == null}">
	<div class="container" align="center">
		<br /> <br /> <br /> <br /> <br />
		<h2>LOGIN</h2>
		<h:form>
			<table>
				<div class="input-group"></div>
				<tr>

					<tr>
						<td><span class="label label-info">E-Mail:</span> <!-- E-mail -->
							<h:inputText value="#{UsuarioLogadoController.user.email}"
								p:placeholder="E-mail" name="e-mail" class="form-control"
								id="email" onblur="checar()"></h:inputText></td>
					</tr>

					<tr>
						<td><span class="label label-info">Senha:</span> <!-- Senha -->
							<h:inputSecret value="#{UsuarioLogadoController.user.senha}"
								p:placeholder="Senha" name="senha" class="form-control"
								id="senha"></h:inputSecret></td>
					</tr>
				</tr>
			</table>
			<tr>
				<h:commandButton value="Logar"
					action="#{UsuarioLogadoController.fazerLogin}" />
				<button type="button" onclick="location.href='index.jsp'">Voltar</button>
			</tr>
		</h:form>

	</div>
	
	</c:if>
	
	
	<c:if test="${UsuarioLogadoController.getEmail() != null}">
	<div class="container" align="center">
		<br /> <br /> <br /> <br /> <br />
		<h2>Logout</h2>
		<h:form>
			<tr>
			
			<h:commandButton value="Logout"
					action="#{UsuarioLogadoController.logout()}" />
			</tr>
		</h:form>

	</div>
	
	</c:if>

	

</h:body>
</html>

forum/src/main/webapp/usuarioSalvo.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:c="http://java.sun.com/jsp/jstl/core" >

<h:head>
	<meta charset="utf-8"></meta>
	<meta http-equiv="X-UA-Compatible" content="IE=edge"></meta>
	<meta name="viewport" content="width=device-width, initial-scale=1"></meta>
	<meta name="description" content=""></meta>
	<meta name="author" content=""></meta>
	<link rel="shortcut icon" href="../../assets/ico/favicon.ico"></link>
	
	<!-- JS -->
	<script type="text/javascript" src="js/jquery.js"></script>
	<script type="text/javascript" src="js/validacao_email.js"></script>
	
	<!-- CSS -->
	<link href="bootstrap3/css/bootstrap.css" rel="stylesheet"></link>
	<link href="bootstrap3/css/bootstrap-theme.css" rel="stylesheet"></link>
	<link href="css/carousel.css" rel="stylesheet"></link>
	<link href="css/validacao_css.css" rel="stylesheet"></link>
	<title>Usuário Salvo</title>
</h:head>
<h:body>
	<div class="navbar-wrapper">
		<div class="container">

			<div class="navbar navbar-inverse navbar-static-top">
				<div class="container">
					<div class="navbar-collapse collapse">
						<ul class="nav navbar-nav">
						<li><a href="index.xhtml">Home</a></li>
							<li><a href="forum.xhtml">Forum</a></li>
							<li><a href="Construcao.xhtml">Conheça o HTML 5</a></li>
							<li><a href="Contato.xhtml">Contato</a></li>
							<li><a href="CadastroUsuario.xhtml">Novo Cadastro</a></li>
							<c:if test="${UsuarioLogadoController.getEmail() != null}">
								<li><a href="UsuarioInformacoes.xhtml">Informações do Usuario</a></li>
							</c:if>
						</ul>
						<c:if test="${UsuarioLogadoController.getEmail() != null}">
							<ul>

								<li><h:outputText style="font-weight:bold" />
									<div class="btn-group">
										<button type="button" class="btn btn-primary dropdown-toggle"
											data-toggle="dropdown" onclick="location.href='login.xhtml'">
											<h:outputText value="#{UsuarioLogadoController.getEmail()}"
												style="font-weight:bold"></h:outputText>
											<span class="glyphicon glyphicon-user"></span> <span
												class="caret"></span>
										</button>
									</div></li>
							</ul>
						</c:if>
						<c:if test="${UsuarioLogadoController.getEmail() eq null}">
							<ul>

								<li><h:outputText style="font-weight:bold" />
									<div class="btn-group">
										<button type="button" class="btn btn-primary dropdown-toggle"
											data-toggle="dropdown" onclick="location.href='login.xhtml'">
											Login
											<span class="glyphicon glyphicon-user"></span> <span
												class="caret"></span>
										</button>
									</div></li>
							</ul>
						</c:if>

					</div>


				</div>
			</div>
		</div>

	</div>

	<br><br><br><br></br></br></br></br>
	<h2>
		<p align="center">Cadastro Realizado com Sucesso!</p>
		<h:outputText value="#{cadastroUsuario.usuario.nome}" style="font-weight:bold" />
	</h2>
	<button type="button" onclick="location.href='forum.xhtml'">Ir para o Forum</button>

	
</h:body>
</html>